config/routes.rb
Rails.application.routes.draw do
 


 root to:  'sessions#welcome'

resources  :users , only:   [:new, :create, :index, :destroy]

resources  :sessions,  only:  [:new, :create, :destroy] 



# # resources  :sessions

# get  'login', to:  'sessions#new'

# post 'login' , to:  'sessions#create'


# delete   'logout' , to:   'sessions#destroy'


# root to: 'sessions#welcome'

  resources :users

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'

# get   'login/edit' , to:  'sessions#edit'

# get   'edit' ,  to:   'sessions#edit'

# put   'update', to:   'sessions#update'

  get   'logout',  to:  'sessions#destroy'
  post  'logout',  to:  'sessions#destroy'

  delete 'logout', to: 'sessions#destroy'


end 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord


     has_secure_password  


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

helper_method   :logged_in?

helper_method   :current_user 


def  current_user   


	User.find_by(id:  session[:user_id])


end 


def  logged_in? 

	!current_user.nil?


end 



end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController


   # before_action :require_none, only: [:new]


def welcome
  end

  def new
  end
  
  def create
    @user = User.find_by(username: params[:username])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      redirect_to '/login'
    end
  end

  def destroy

# User.find(session[:user_id]).destroy    

    session.clear
    redirect_to  '/login'


    # log_out if logged_in?
    # redirect_to root_path


  end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController


before_action :set_user, only: [:show, :edit, :update, :destroy]

 before_action :admin_user,     only: :destroy

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else 
      render :new
    end
  end

  def show
  end

  def edit
    if !logged_in? || !@user
      redirect_to root_path
       # @user = User.find(params[:id])
    end
  end
      
  def update
    if @user
      @user.update(user_params)

      if @user.errors.any?
        render "edit"
      else
        redirect_to user_path(@user)
      end
    else
      render "edit"
    end
  end

  def destroy
    @user.destroy
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end

  def set_user
    @user = User.find_by_id(params[:id])
  end


# def index
#   # @users = User.paginate(page:  params[:page_load)

# end 



end

app/helpers/application_helper.rb
module ApplicationHelper












	
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def log_in(user)
        session[:user_id] = user.id
      end

      # Returns the current logged-in user (if any).
      def current_user
        @current_user ||= User.find_by(id: session[:user_id])
      end

      def logged_in?
        !current_user.nil?
      end

      def log_out
        session.delete(:user_id)
        @current_user = nil
      end

      def destroy
        log_out
        redirect_to '/login'
      end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_nav.erb
<% if !logged_in? %>
  <%= link_to "Login", login_path %>
  <%= link_to "Sign Up", new_user_path %>
<% elsif %>
  <%= link_to "Log Out", logout_path, method: :delete %>
<%  else%>
<%=  link_to  "destroy", logout_path,  method:  :deslete  %>


<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UserApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
<body>
  <%= render 'layouts/nav' %>
  <%= yield %>
</body>

</html>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

<li>
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>




<h1>Would you like to Edit your Account Details?</h1>

<%= form_with model: @user, local: true do |f| %>
  <%= f.label :username %><br>
  <%= f.text_field :username, autofocus: true %><br>

  <%= f.label :password %><br>
  <%= f.password_field :password %><br>

  <%= f.submit "Confirm Changes" %>
<% end %>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>


<h1>Would you like to Sign Up?</h1>

<%= form_with model: @user, local: true do |f| %>
  <%= f.label :username %><br>
  <%= f.text_field :username, autofocus: true %><br>

  <%= f.label :password %><br>
  <%= f.password_field :password %><br>

  <%= f.submit "Sign Up" %>
<% end %>  

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>



<h1>Welcome <%= current_user.username %></h1>
<%= link_to "Edit Account", edit_user_path(current_user) %>
<%= link_to "Delete Account", current_user, data: { confirm: "Are you sure?" }, method: :delete %>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>